# Generated by Django 4.1.4 on 2022-12-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cpassword_forms_conformpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='id',
        ),
        migrations.AlterField(
            model_name='forms',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Lforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.forms')),
            ],
        ),
    ]
